"""Expose Rooms while keeping Snapshot capture and persistence private.

`RoomLord.corresponding_room` applies the active Tab's law for manifest and
returns a `Room` plus the current Snapshot key. `RoomLord.find_room` recovers the
containing Room from an existing key for follow-up operations. A Room exposes
Snapshot metadata, repository-relative filepath pairs, and direct lookup of the
absolute captured files under a caller-supplied Snapshot key; it never retains a
selected key itself.

The private store captures affected files, hashes their contents, publishes
immutable directories, and delegates relational work to `RoomStore`. Neither
the store nor its capture operations are part of this module's public surface.
This module does not build HTTP responses, select diff engines, or render files.
"""

from __future__ import annotations

import fcntl
import hashlib
import json
import shutil
import tempfile
from collections.abc import Iterator
from pathlib import Path
from threading import Lock
from typing import Literal, Optional, TypedDict
from uuid import UUID, uuid4

from dirdiff.backend import (
    BranchSelection,
    GitBackend,
    LazyReason,
    PresetBackend,
    WorkspaceBackendProtocol,
)
from dirdiff.db import (
    RoomIdentity,
    RoomStore,
    SnapshotFileRecord,
    SnapshotFileSideRecord,
    SnapshotMetaRecord,
    SnapshotRecord,
)
from dirdiff.engines import DirdiffError

__all__ = [
    "FileMeta",
    "Room",
    "RoomLord",
    "SnapshotMeta",
]

RoomTab = Literal[
    "head",
    "refs",
    "branch-review",
    "pull-request",
    "preset",
]
"""One supported Tab identity used by the law of correspondence.

Values outside these five categories are invalid at `RoomLord`'s boundary and
must never reach capture or persistence.
"""

ChangeType = Literal["modify", "add", "delete", "rename", "copy"]
"""Stable backend classification for one captured filepath pair.

The value records path-level repository state. It must not represent renderer
output, line alignment, or lazy-loading policy.
"""

_SNAPSHOT_HASH_DOMAIN = b"dirdiff-snapshot-v5"
_CAPTURE_ERROR_PREAMBLE = (
    "MACHINE-GENERATED BY DIRDIFF\nThe original file could not be captured."
)


class SnapshotMeta(TypedDict):
    """Metadata captured for a complete Snapshot.

    `tab` exposes the containing Room's persisted identity for HTTP
    presentation without storing it again on the Snapshot. Labels identify the
    two captured sides. Aggregate line counts come directly from the workspace
    backend; both are `None` when that backend cannot state them authoritatively.
    """

    tab: RoomTab
    left_label: str
    right_label: str
    added_lines: Optional[int]
    removed_lines: Optional[int]


class FileMeta(TypedDict):
    """Stable backend facts accompanying one captured filepath pair.

    The metadata preserves tracked provenance, Git/preset change
    classification, and an explicit backend lazy override. It contains no
    renderer output or per-File line counts.
    """

    tracked: bool
    change_type: ChangeType
    lazy_reason_override: Optional[LazyReason]


class Room:
    """Provide immutable file state for one correspondence-selected Room.

    A Room can contain many Snapshots. `meta`, `manifested`, and `get` therefore
    require the exact Snapshot key on every call. The class never stores a
    selected Snapshot id or exposes its private publication store.
    """

    def __init__(
        self,
        *,
        database: RoomStore,
        identity: RoomIdentity,
    ) -> None:
        """Create a Room over one correspondence identity.

        Only `RoomLord` constructs this object. The supplied identity limits
        every relational read to this Room but does not select a Snapshot;
        callers must pass the exact key to every public read.
        """
        self._database = database
        self._identity = identity

    def meta(self, snapshot_id: UUID) -> SnapshotMeta:
        """Return retained Snapshot facts and the containing Room's Tab.

        `snapshot_id` must name a Snapshot belonging to this Room. Unknown or
        cross-Room keys are rejected instead of producing substitute metadata.
        The Tab comes from the Room identity and is not duplicated in Snapshot
        persistence.
        """
        record = self._database.snapshot_meta(self._identity, snapshot_id.hex)
        if record is None:
            raise DirdiffError(f"Unknown snapshot id: {snapshot_id.hex}")
        match self._identity.tab:
            case "head" | "refs" | "branch-review" | "pull-request" | "preset":
                tab: RoomTab = self._identity.tab
            case _:
                raise AssertionError(
                    f"invalid persisted Room Tab: {self._identity.tab!r}"
                )
        return {
            "tab": tab,
            "left_label": record.left_label,
            "right_label": record.right_label,
            "added_lines": record.added_lines,
            "removed_lines": record.removed_lines,
        }

    def manifested(
        self,
        snapshot_id: UUID,
    ) -> Iterator[
        tuple[
            Optional[Path],
            Optional[Path],
            FileMeta,
        ]
    ]:
        """Yield manifested files and their metadata.

        The Paths are repository-relative paths, includes even errored files.
        """
        record = self._database.snapshot(self._identity, snapshot_id.hex)
        if record is None:
            raise DirdiffError(f"Unknown snapshot id: {snapshot_id.hex}")
        persisted_reasons = self._database.snapshot_lazy_reasons(
            self._identity,
            snapshot_id.hex,
        )
        lazy_reasons: dict[str, LazyReason] = {}
        for file_id, reason in persisted_reasons.items():
            match reason:
                case (
                    "too_big"
                    | "generated"
                    | "deleted"
                    | "untracked"
                    | "pure_renamed"
                ):
                    lazy_reasons[file_id] = reason
                case _:
                    raise AssertionError(
                        f"invalid persisted lazy reason: {reason!r}"
                    )
        file_ids = {file.id for file in record.files}
        assert lazy_reasons.keys() <= file_ids, (
            "lazy reasons must identify Files in their Snapshot"
        )
        for file in record.files:
            match file.change_type:
                case "modify" | "add" | "delete" | "rename" | "copy":
                    change_type: ChangeType = file.change_type
                case _:
                    raise AssertionError(
                        "invalid persisted File change type: "
                        f"{file.change_type!r}"
                    )
            lazy_reason = lazy_reasons.get(file.id)
            yield (
                Path(file.left.repository_path)
                if file.left is not None
                else None,
                Path(file.right.repository_path)
                if file.right is not None
                else None,
                {
                    "tracked": file.tracked,
                    "change_type": change_type,
                    "lazy_reason_override": lazy_reason,
                },
            )

    def get(
        self,
        snapshot_id: UUID,
        left: Optional[Path],
        right: Optional[Path],
    ) -> tuple[Optional[Path], Optional[Path], FileMeta]:
        """Return physical files and their metadata for one filepath pair.

        Input Paths are repository-relative. Returned Paths are absolute paths to
        the persisted files.

        # Raises
          - `DirdiffError` with the persisted reason for an errored file.
        """
        if left is None and right is None:
            raise DirdiffError("left or right filepath is required.")

        for path in (left, right):
            if path is not None and (path.is_absolute() or ".." in path.parts):
                raise DirdiffError(
                    f"Room filepath must be repository-relative: {path}"
                )
            if path is not None and path.as_posix() in {"", "."}:
                raise DirdiffError("Room filepath must identify a file.")

        snapshot_exists, loaded = self._database.snapshot_file(
            self._identity,
            snapshot_id=snapshot_id.hex,
            left_path=left.as_posix() if left is not None else None,
            right_path=right.as_posix() if right is not None else None,
        )
        if not snapshot_exists:
            raise DirdiffError(f"Unknown snapshot id: {snapshot_id.hex}")
        if loaded is None:
            raise DirdiffError("Snapshot manifest path is missing.")
        file = loaded.file
        if file.error is not None:
            raise DirdiffError(file.error)
        directory = Path(file.path)
        assert directory.is_absolute(), (
            f"persisted Snapshot File path is not absolute: {file.path!r}"
        )
        result: list[Optional[Path]] = []
        for name, side in (("left", file.left), ("right", file.right)):
            if side is None:
                result.append(None)
                continue
            path = directory / name
            content = path.read_bytes()
            assert hashlib.sha256(content).digest() == side.content_hash, (
                f"Snapshot File content hash mismatch: {path}"
            )
            result.append(path)
        assert len(result) == 2
        match file.change_type:
            case "modify" | "add" | "delete" | "rename" | "copy":
                change_type = file.change_type
            case _:
                raise AssertionError(
                    f"invalid persisted File change type: {file.change_type!r}"
                )
        lazy_reason: Optional[LazyReason] = None
        if loaded.lazy_reason is not None:
            match loaded.lazy_reason:
                case (
                    "too_big"
                    | "generated"
                    | "deleted"
                    | "untracked"
                    | "pure_renamed"
                ):
                    lazy_reason = loaded.lazy_reason
                case _:
                    raise AssertionError(
                        f"invalid persisted lazy reason: {loaded.lazy_reason!r}"
                    )
        return (
            result[0],
            result[1],
            {
                "tracked": file.tracked,
                "change_type": change_type,
                "lazy_reason_override": lazy_reason,
            },
        )


class RoomLord:
    """Apply the active Tab's law of correspondence and return a Room.

    `corresponding_room` applies the law for a manifest operation and returns
    both the Room and the captured Snapshot key. `find_room` uses an existing
    Snapshot key to recover its Room for follow-up operations. Neither method
    exposes the private Snapshot store.
    """

    def __init__(self, database: RoomStore, store_path: Path) -> None:
        """Create the application boundary for one database and store root.

        The paths are normalized but not created here. This keeps construction
        harmless; the first valid manifest capture creates storage only after
        repository-placement checks succeed.
        """
        self._database = database
        self._store_path = store_path.expanduser().resolve()
        self._staging_path = self._store_path / "staging"
        self._snapshots_path = self._store_path / "snapshots"
        database_path = self._database.engine.url.database
        if database_path is None or database_path == ":memory:":
            self._lock_path = self._store_path / "store.lock"
        else:
            database_file = Path(database_path).expanduser().resolve()
            self._lock_path = database_file.with_name(
                f"{database_file.name}.room.lock"
            )
        # `flock` coordinates processes; this lock gives worker threads one
        # unambiguous publication critical section.
        self._thread_lock = Lock()

    def corresponding_room(
        self,
        *,
        mark_id: Optional[int],
        tab: RoomTab,
        backend: WorkspaceBackendProtocol,
        branch_selections: tuple[
            Optional[BranchSelection],
            Optional[BranchSelection],
        ],
        left: Optional[str],
        right: Optional[str],
        preset_catalog: Optional[str],
        preset_subset: Optional[str],
        show_untracked: bool,
    ) -> tuple[Room, UUID]:
        """Apply one Tab's law and return its Room and current Snapshot key.

        Every keyword is required because the server supplies one complete Tab
        state. Values that do not apply to that Tab must be `None`; applicable
        values are asserted or rejected here. Commit-backed refs are frozen
        before Room selection, while branch-backed Tabs retain their structured
        symbolic selections as correspondence identity.
        """
        repo_root = backend.repo_root
        if mark_id is not None and repo_root is not None:
            reviewed_root = repo_root.resolve()
            database = self._database.engine.url.database
            if database is not None and database != ":memory:":
                database_path = Path(database).expanduser().resolve()
                if database_path.is_relative_to(reviewed_root):
                    raise DirdiffError(
                        "The dirdiff database must be outside the reviewed "
                        f"repository: {database_path}"
                    )
            if self._store_path.is_relative_to(reviewed_root):
                raise DirdiffError(
                    "The dirdiff Snapshot store must be outside the reviewed "
                    f"repository: {self._store_path}"
                )

        selected_base, selected_review = branch_selections
        git_backend: Optional[GitBackend] = None
        if tab != "preset":
            assert isinstance(backend, GitBackend), (
                "repository Rooms require GitBackend"
            )
            git_backend = backend

        if tab == "preset":
            assert mark_id is None, "preset Rooms cannot belong to a Mark"
            assert selected_base is None and selected_review is None
            assert left is None and right is None
            if (
                preset_catalog is None
                or (catalog := preset_catalog.strip()) == ""
            ):
                raise DirdiffError(
                    "preset_catalog is required for preset mode."
                )
            if preset_subset is None or (subset := preset_subset.strip()) == "":
                raise DirdiffError("preset_subset is required for preset mode.")
            left_side = backend.normalize_side(subset)
            right_side = "new"
            left_label = "old"
            right_label = "new"
            correspondence: object = {"catalog": catalog, "subset": subset}
        elif tab in {"branch-review", "pull-request"}:
            assert mark_id is not None, "branch Rooms require a Mark"
            assert left is None and right is None
            assert preset_catalog is None and preset_subset is None
            if selected_base is None or selected_review is None:
                raise DirdiffError("branch selections are required.")
            assert not show_untracked, (
                "branch-backed Tabs do not support intruding Files"
            )
            assert git_backend is not None
            resolved_base, left_side, review = (
                git_backend.resolve_branch_diff_sides(
                    base_selection=selected_base,
                    review_selection=selected_review,
                )
            )
            right_side = git_backend.commit_id(review)
            left_label = f"{resolved_base.strip()}...{review}"
            right_label = review
            correspondence = {"base": selected_base, "review": selected_review}
        elif tab == "head":
            assert mark_id is not None, "Diff against HEAD requires a Mark"
            assert selected_base is None and selected_review is None
            assert preset_catalog is None and preset_subset is None
            if left is None or right is None:
                raise DirdiffError(
                    "Diff against HEAD requires HEAD and worktree sides."
                )
            left_label = backend.normalize_side(left.strip())
            right_label = backend.normalize_side(right.strip())
            if left_label != "HEAD" or right_label != "worktree":
                raise DirdiffError(
                    "Diff against HEAD requires left=HEAD and right=worktree."
                )
            assert git_backend is not None
            left_side = git_backend.commit_id(left_label)
            right_side = right_label
            correspondence = {"commit": left_side}
        elif tab == "refs":
            assert mark_id is not None, "repo Rooms require a Mark"
            assert selected_base is None and selected_review is None
            assert preset_catalog is None and preset_subset is None
            assert git_backend is not None
            if left is None or left.strip() == "":
                raise DirdiffError("left is required for this diff mode.")
            if right is None or right.strip() == "":
                raise DirdiffError("right is required for this diff mode.")
            left_label = backend.normalize_side(left.strip())
            right_label = backend.normalize_side(right.strip())
            left_side = (
                left_label
                if left_label in {"index", "worktree"}
                else git_backend.commit_id(left_label)
            )
            right_side = (
                right_label
                if right_label in {"index", "worktree"}
                else git_backend.commit_id(right_label)
            )
            left_label = left_side
            right_label = right_side
            correspondence = {"left": left_side, "right": right_side}
        else:
            raise AssertionError(f"invalid Room Tab: {tab!r}")

        identity = RoomIdentity(
            mark_id=mark_id,
            tab=tab,
            correspondence_key=json.dumps(
                correspondence,
                sort_keys=True,
                separators=(",", ":"),
            ).encode(),
        )
        store = _SnapshotStore(
            database=self._database,
            staging_path=self._staging_path,
            snapshots_path=self._snapshots_path,
            lock_path=self._lock_path,
            thread_lock=self._thread_lock,
            identity=identity,
        )
        snapshot_id = store.capture(
            backend=backend,
            left_side=left_side,
            right_side=right_side,
            left_label=left_label,
            right_label=right_label,
            show_untracked=show_untracked,
        )
        return Room(database=self._database, identity=identity), snapshot_id

    def find_room(self, snapshot_id: UUID) -> Room:
        """Return the Room containing an existing Snapshot key.

        The Snapshot id is globally unique in this database. Missing keys are
        rejected; this lookup neither executes a Tab law nor reads live backend
        state.
        """
        identity = self._database.room_identity(snapshot_id.hex)
        if identity is None:
            raise DirdiffError(f"Unknown snapshot id: {snapshot_id.hex}")
        if identity.tab not in {
            "head",
            "refs",
            "branch-review",
            "pull-request",
            "preset",
        }:
            raise AssertionError(
                f"invalid persisted Room Tab: {identity.tab!r}"
            )
        return Room(database=self._database, identity=identity)


class _SnapshotStore:
    """Implement immutable Snapshot capture for one private Room.

    `RoomLord` constructs and calls the store while applying correspondence.
    It manages publication directories, locking, relational records, and digest
    validation; returned `Room` objects and API code never receive it.
    """

    def __init__(
        self,
        *,
        database: RoomStore,
        staging_path: Path,
        snapshots_path: Path,
        lock_path: Path,
        thread_lock: Lock,
        identity: RoomIdentity,
    ) -> None:
        """Create private persistence access for exactly one Room identity.

        `RoomLord` supplies shared paths and locking, while `identity` limits
        every relational lookup. Constructing the store performs no filesystem
        or database work.
        """
        assert identity.correspondence_key != b"", (
            "Room correspondence key cannot be empty"
        )
        self._database = database
        self._staging_path = staging_path
        self._snapshots_path = snapshots_path
        self._lock_path = lock_path
        self._thread_lock = thread_lock
        self._identity = identity

    def capture(
        self,
        *,
        backend: WorkspaceBackendProtocol,
        left_side: str,
        right_side: str,
        left_label: str,
        right_label: str,
        show_untracked: bool,
    ) -> UUID:
        """Capture current backend state and return its retained Snapshot key.

        Equality includes repository paths, tracked provenance, change type,
        captured contents, capture errors, and complete explicit preset metadata.
        Backend order, human labels, and aggregate line counts do not affect
        identity.
        """
        self._staging_path.mkdir(parents=True, exist_ok=True)
        self._snapshots_path.mkdir(parents=True, exist_ok=True)
        self._lock_path.touch(exist_ok=True)

        paths = backend.list_repo_diff_paths(
            left=left_side,
            right=right_side,
            show_untracked=show_untracked,
        )
        added_lines, removed_lines = backend.line_counts(
            left=left_side,
            right=right_side,
            show_untracked=show_untracked,
        )
        assert (added_lines is None) == (removed_lines is None), (
            "backend aggregate line counts must have equal presence"
        )
        captured: list[
            tuple[
                Optional[str],
                Optional[bytes],
                Optional[str],
                Optional[bytes],
                bool,
                ChangeType,
                Optional[LazyReason],
                Optional[str],
                Optional[str],
            ]
        ] = []
        captured_paths: set[tuple[Optional[str], Optional[str]]] = set()
        for path in paths:
            repository_paths = (path.left_path, path.right_path)
            if repository_paths in captured_paths:
                raise DirdiffError(
                    "Backend returned duplicate left/right paths: "
                    f"{repository_paths!r}"
                )
            captured_paths.add(repository_paths)
            left_path = (
                backend.normalize_repo_path(path.left_path)
                if path.left_path is not None
                else None
            )
            right_path = (
                backend.normalize_repo_path(path.right_path)
                if path.right_path is not None
                else None
            )
            errors: list[str] = []
            left_content: Optional[bytes] = None
            if left_path is not None:
                try:
                    left_content = backend.load_version(left_path, left_side)
                except DirdiffError as exc:
                    failure = (
                        f"Could not capture left side {left_side}:{left_path}: "
                        f"{exc}"
                    )
                    errors.append(failure)
                    left_content = (
                        f"{_CAPTURE_ERROR_PREAMBLE}\n\n{failure}\n".encode()
                    )
            right_content: Optional[bytes] = None
            if right_path is not None:
                try:
                    right_content = backend.load_version(right_path, right_side)
                except DirdiffError as exc:
                    failure = (
                        f"Could not capture right side {right_side}:{right_path}: "
                        f"{exc}"
                    )
                    errors.append(failure)
                    right_content = (
                        f"{_CAPTURE_ERROR_PREAMBLE}\n\n{failure}\n".encode()
                    )
            assert (left_path is None) == (left_content is None), (
                "left repository path and captured contents must have equal presence"
            )
            assert (right_path is None) == (right_content is None), (
                "right repository path and captured contents must have equal presence"
            )
            assert left_content is not None or right_content is not None, (
                "Snapshot File must have at least one side"
            )

            lazy_metadata: Optional[tuple[LazyReason, str]] = None
            if self._identity.tab == "preset":
                assert isinstance(backend, PresetBackend), (
                    "preset Rooms require PresetBackend"
                )
                assert path.right_path is not None, (
                    "preset Files require a right repository path"
                )
                lazy_metadata = backend.lazy_reason_metadata(path.right_path)
                assert (
                    lazy_metadata[0] if lazy_metadata is not None else None
                ) == path.lazy_reason_override, (
                    "preset lazy reason changed during Snapshot capture"
                )
            else:
                assert lazy_metadata is None
            captured.append(
                (
                    left_path,
                    left_content,
                    right_path,
                    right_content,
                    not path.untracked,
                    path.change_type,
                    path.lazy_reason_override,
                    lazy_metadata[1] if lazy_metadata is not None else None,
                    "\n".join(errors) if errors else None,
                )
            )

        # Canonicalization makes the digest describe a set of Files; it does not
        # define storage or manifest presentation order.
        captured.sort(key=lambda item: (item[0] or "", item[2] or ""))
        digest = hashlib.sha256()
        digest.update(_SNAPSHOT_HASH_DOMAIN)
        for (
            left_path,
            left_content,
            right_path,
            right_content,
            tracked,
            change_type,
            lazy_reason,
            metadata_content,
            error,
        ) in captured:
            for value in (
                left_path.encode() if left_path is not None else None,
                left_content,
                right_path.encode() if right_path is not None else None,
                right_content,
                b"1" if tracked else b"0",
                change_type.encode(),
                lazy_reason.encode() if lazy_reason is not None else None,
                metadata_content.encode()
                if metadata_content is not None
                else None,
                error.encode() if error is not None else None,
            ):
                if value is None:
                    digest.update(b"\x00")
                else:
                    digest.update(b"\x01")
                    digest.update(len(value).to_bytes(8, "big"))
                    digest.update(value)
        snapshot_hash = digest.digest()

        snapshot_id = uuid4()
        staging_path = Path(
            tempfile.mkdtemp(
                prefix=f"{snapshot_id.hex}-",
                dir=self._staging_path,
            )
        )
        final_path = (self._snapshots_path / snapshot_id.hex).resolve()
        files: list[SnapshotFileRecord] = []
        lazy_reasons: dict[str, tuple[str, Optional[str]]] = {}
        try:
            for (
                left_path,
                left_content,
                right_path,
                right_content,
                tracked,
                change_type,
                lazy_reason,
                metadata_content,
                error,
            ) in captured:
                file_id = uuid4().hex
                file_path = staging_path / file_id
                file_path.mkdir()
                left_record: Optional[SnapshotFileSideRecord] = None
                if left_path is not None and left_content is not None:
                    (file_path / "left").write_bytes(left_content)
                    left_record = SnapshotFileSideRecord(
                        repository_path=left_path,
                        content_hash=hashlib.sha256(left_content).digest(),
                    )
                right_record: Optional[SnapshotFileSideRecord] = None
                if right_path is not None and right_content is not None:
                    (file_path / "right").write_bytes(right_content)
                    right_record = SnapshotFileSideRecord(
                        repository_path=right_path,
                        content_hash=hashlib.sha256(right_content).digest(),
                    )
                files.append(
                    SnapshotFileRecord(
                        id=file_id,
                        snapshot_id=snapshot_id.hex,
                        path=str(final_path / file_id),
                        tracked=tracked,
                        change_type=change_type,
                        error=error,
                        left=left_record,
                        right=right_record,
                    )
                )
                if lazy_reason is not None:
                    lazy_reasons[file_id] = lazy_reason, metadata_content

            with self._thread_lock, self._lock_path.open("a+b") as lock_file:
                fcntl.flock(lock_file.fileno(), fcntl.LOCK_EX)
                try:
                    visible_id = self._database.snapshot_id_for_content(
                        self._identity,
                        snapshot_hash,
                    )
                    if visible_id is None:
                        staging_path.rename(final_path)
                        self._database.publish(
                            self._identity,
                            SnapshotRecord(
                                id=snapshot_id.hex,
                                content_hash=snapshot_hash,
                                meta=SnapshotMetaRecord(
                                    left_label=left_label,
                                    right_label=right_label,
                                    added_lines=added_lines,
                                    removed_lines=removed_lines,
                                ),
                                files=tuple(files),
                            ),
                            lazy_reasons=lazy_reasons,
                        )
                        visible_id = snapshot_id.hex
                    else:
                        visible_snapshot = self._database.snapshot(
                            self._identity,
                            visible_id,
                        )
                        assert visible_snapshot is not None, (
                            "equal Snapshot disappeared during publication"
                        )
                        for file in visible_snapshot.files:
                            directory = Path(file.path)
                            for name, side in (
                                ("left", file.left),
                                ("right", file.right),
                            ):
                                if side is None:
                                    continue
                                captured_path = directory / name
                                content = captured_path.read_bytes()
                                assert (
                                    hashlib.sha256(content).digest()
                                    == side.content_hash
                                ), (
                                    "Snapshot File content hash mismatch: "
                                    f"{captured_path}"
                                )
                    return UUID(hex=visible_id)
                finally:
                    fcntl.flock(lock_file.fileno(), fcntl.LOCK_UN)
        finally:
            if staging_path.exists():
                shutil.rmtree(staging_path)
