"""Expose Rooms while keeping Snapshot capture and persistence private.

`RoomLord.corresponding_room` applies the active Tab's law for an explicit
capture and returns a `Room` plus the current Snapshot key.
`RoomLord.find_room` recovers the containing Room from an existing key for
follow-up operations; RoomLord does nothing else. A Room contains Snapshots
and Threads. It exposes Snapshot metadata, repository-relative filepath pairs,
direct lookup of the absolute captured files, Thread access, and continuation
of its own persisted Tab (`capture_context`, `recapture`, `path_for_snapshot`)
under a caller-supplied Snapshot key; it never retains a selected key itself.
A bound Thread performs Comment and lifecycle operations and privately
interprets its placement.

The private store captures affected files, hashes their contents, publishes
immutable directories, and delegates relational work to `RoomStore`. Neither
the store nor its capture operations are part of this module's public surface.
This module does not build HTTP responses, select diff engines, or render files.
"""

from __future__ import annotations

import fcntl
import hashlib
import json
import shutil
import tempfile
from collections.abc import Iterator
from dataclasses import dataclass
from pathlib import Path
from threading import Lock
from typing import Literal, Optional, TypedDict
from uuid import UUID, uuid4

from dirdiff.backend import (
    BranchSelection,
    GitBackend,
    LazyReason,
    PresetBackend,
    WorkspaceBackendProtocol,
)
from dirdiff.db import (
    ReviewActionRecord,
    RoomIdentity,
    RoomStore,
    SnapshotFileRecord,
    SnapshotFileSideRecord,
    SnapshotMetaRecord,
    SnapshotRecord,
    UserProfileRecord,
)
from dirdiff.engines import DirdiffError
from dirdiff.review import (
    CreateThread,
    ReviewBatchAction,
    ReviewBatchResult,
    ReviewError,
    Thread,
    apply_review_batch,
    create_thread,
    derive_room_threads,
    get_thread,
    thread_objects,
)

__all__ = [
    "BranchReviewCaptureSelection",
    "CaptureSelection",
    "FileMeta",
    "PresetCaptureSelection",
    "PresetCatalog",
    "PullRequestCaptureSelection",
    "RevisionsCaptureSelection",
    "Room",
    "RoomLord",
    "SnapshotMeta",
    "Thread",
]

RoomTab = Literal[
    "head",
    "refs",
    "branch-review",
    "pull-request",
    "preset",
]
"""One supported Tab identity used by the law of correspondence.

Values outside these five categories are invalid at `RoomLord`'s boundary and
must never reach capture or persistence.
"""

ChangeType = Literal["modify", "add", "delete", "rename", "copy"]


@dataclass(frozen=True)
class RevisionsCaptureSelection:
    """Select the head or refs Tab: two explicit side names of one Mark.

    `tab` distinguishes the HEAD/worktree contract (which may include
    untracked worktree Files) from arbitrary refs. Sides are the raw caller
    spellings; correspondence normalizes and freezes them.
    """

    tab: Literal["head", "refs"]
    left: str
    right: str
    show_untracked: bool


@dataclass(frozen=True)
class BranchReviewCaptureSelection:
    """Select the Branch Review Tab: symbolic base and review branches."""

    base: BranchSelection
    review: BranchSelection


@dataclass(frozen=True)
class PullRequestCaptureSelection:
    """Select the Pull Request Tab: prepared URL and frozen commit ids.

    Preparation already resolved the forge URL and froze both commits;
    correspondence only re-validates that the ids are complete commits.
    """

    url: str
    left_commit: str
    right_commit: str


# The closed set of preset catalogs; each backs one Mark-less Room family.
PresetCatalog = Literal["diff", "fold", "gumtree", "scroll", "notebook"]


@dataclass(frozen=True)
class PresetCaptureSelection:
    """Select the Preset Tab: one validated catalog and fixture group."""

    catalog: PresetCatalog
    subset: str


# One concrete Tab selection: each variant carries exactly the fields its
# Tab's law consumes, so callers never manufacture irrelevant nulls and the
# law never branches on cross-Tab nullability.
CaptureSelection = (
    RevisionsCaptureSelection
    | BranchReviewCaptureSelection
    | PullRequestCaptureSelection
    | PresetCaptureSelection
)
"""Stable backend classification for one captured filepath pair.

The value records path-level repository state. It must not represent renderer
output, line alignment, or lazy-loading policy.
"""

_SNAPSHOT_HASH_DOMAIN = b"dirdiff-snapshot-v6"
_CAPTURE_ERROR_PREAMBLE = (
    "MACHINE-GENERATED BY DIRDIFF\nThe original file could not be captured."
)


class SnapshotMeta(TypedDict):
    """Metadata captured for a complete Snapshot.

    `tab` exposes the containing Room's persisted identity for HTTP
    presentation without storing it again on the Snapshot. Labels identify the
    two captured sides. Aggregate line counts come directly from the workspace
    backend; both are `None` when that backend cannot state them authoritatively.
    """

    tab: RoomTab
    left_label: str
    right_label: str
    added_lines: Optional[int]
    removed_lines: Optional[int]


class RoomCaptureContext(TypedDict):
    """Expose only the persisted facts needed to continue one agent review.

    Agent review supports repository-backed Tabs. The Mark identifies the
    already registered workspace, while a Pull Request additionally exposes
    its canonical URL so the HTTP boundary can prepare its current commits.
    """

    tab: Literal["head", "refs", "branch-review", "pull-request"]
    mark_id: int
    pull_request_url: Optional[str]


class FileMeta(TypedDict):
    """Stable backend facts accompanying one captured filepath pair.

    The metadata preserves tracked provenance, Git/preset change
    classification, an explicit backend lazy override, and the exact capture
    failure when publication could not retain the File contents. It contains
    no renderer output or per-File line counts.
    """

    tracked: bool
    change_type: ChangeType
    lazy_reason_override: Optional[LazyReason]
    capture_error: Optional[str]


class SnapshotFileDelta(TypedDict):
    """List captured File sides added, changed, and removed between Snapshots."""

    added: tuple[Path, ...]
    changed: tuple[Path, ...]
    removed: tuple[Path, ...]


class Room:
    """Own one correspondence-selected Room's Snapshots and hand out Threads.

    Snapshot reads (`meta`, `manifested`, `get`, `file_delta`, the captured-file
    lookups) and Thread access (`threads`, `get_thread`, `thread_for_comment`,
    `create_thread`, `apply_review_batch`, the activity reads) require the exact
    Snapshot key on every call. Comment and lifecycle writes are the returned
    bound Threads' responsibility; Room only locates and constructs them.
    `capture_context`, `recapture`, and `path_for_snapshot` continue this Room's
    persisted Tab with new captures. The class never stores a selected Snapshot
    id or exposes its private publication store.
    """

    def __init__(
        self,
        *,
        database: RoomStore,
        identity: RoomIdentity,
        staging_path: Path,
        snapshots_path: Path,
        lock_path: Path,
        thread_lock: Lock,
    ) -> None:
        """Create a Room over one correspondence identity.

        Only `RoomLord` constructs this object. The supplied identity limits
        every relational read to this Room but does not select a Snapshot;
        callers must pass the exact key to every public read. The store paths
        locate this Room's durable Snapshot directories and staging area.
        """
        self._database = database
        self._identity = identity
        self._staging_path = staging_path
        self._snapshots_path = snapshots_path
        self._lock_path = lock_path
        self._thread_lock = thread_lock

    def meta(self, snapshot_id: UUID) -> SnapshotMeta:
        """Return retained Snapshot facts and the containing Room's Tab.

        `snapshot_id` must name a Snapshot belonging to this Room. Unknown or
        cross-Room keys are rejected instead of producing substitute metadata.
        The Tab comes from the Room identity and is not duplicated in Snapshot
        persistence.
        """
        record = self._database.snapshot_meta(self._identity, snapshot_id.hex)
        if record is None:
            raise DirdiffError(f"Unknown snapshot id: {snapshot_id.hex}")
        match self._identity.tab:
            case "head" | "refs" | "branch-review" | "pull-request" | "preset":
                tab: RoomTab = self._identity.tab
            case _:
                raise AssertionError(
                    f"invalid persisted Room Tab: {self._identity.tab!r}"
                )
        return {
            "tab": tab,
            "left_label": record.left_label,
            "right_label": record.right_label,
            "added_lines": record.added_lines,
            "removed_lines": record.removed_lines,
        }

    def manifested(
        self,
        snapshot_id: UUID,
    ) -> Iterator[
        tuple[
            Optional[Path],
            Optional[Path],
            FileMeta,
        ]
    ]:
        """Yield manifested files and their metadata.

        The Paths are repository-relative paths, includes even errored files.
        """
        record = self._database.snapshot(self._identity, snapshot_id.hex)
        if record is None:
            raise DirdiffError(f"Unknown snapshot id: {snapshot_id.hex}")
        persisted_reasons = self._database.snapshot_lazy_reasons(
            self._identity,
            snapshot_id.hex,
        )
        lazy_reasons: dict[str, LazyReason] = {}
        for file_id, reason in persisted_reasons.items():
            match reason:
                case (
                    "too_big"
                    | "generated"
                    | "deleted"
                    | "untracked"
                    | "pure_renamed"
                ):
                    lazy_reasons[file_id] = reason
                case _:
                    raise AssertionError(
                        f"invalid persisted lazy reason: {reason!r}"
                    )
        file_ids = {file.id for file in record.files}
        assert lazy_reasons.keys() <= file_ids, (
            "lazy reasons must identify Files in their Snapshot"
        )
        for file in record.files:
            match file.change_type:
                case "modify" | "add" | "delete" | "rename" | "copy":
                    change_type: ChangeType = file.change_type
                case _:
                    raise AssertionError(
                        "invalid persisted File change type: "
                        f"{file.change_type!r}"
                    )
            lazy_reason = lazy_reasons.get(file.id)
            yield (
                Path(file.left.repository_path)
                if file.left is not None
                else None,
                Path(file.right.repository_path)
                if file.right is not None
                else None,
                {
                    "tracked": file.tracked,
                    "change_type": change_type,
                    "lazy_reason_override": lazy_reason,
                    "capture_error": file.error,
                },
            )

    def get(
        self,
        snapshot_id: UUID,
        left: Optional[Path],
        right: Optional[Path],
    ) -> tuple[Optional[Path], Optional[Path], FileMeta]:
        """Return physical files and their metadata for one filepath pair.

        Input Paths are repository-relative. Returned Paths are absolute paths to
        the persisted files.

        A captured File failure is returned in `FileMeta.capture_error`; callers
        decide whether their boundary presents or classifies that exact reason.
        """
        if left is None and right is None:
            raise DirdiffError("left or right filepath is required.")

        for path in (left, right):
            if path is not None and (path.is_absolute() or ".." in path.parts):
                raise DirdiffError(
                    f"Room filepath must be repository-relative: {path}"
                )
            if path is not None and path.as_posix() in {"", "."}:
                raise DirdiffError("Room filepath must identify a file.")

        snapshot_exists, loaded = self._database.snapshot_file(
            self._identity,
            snapshot_id=snapshot_id.hex,
            left_path=left.as_posix() if left is not None else None,
            right_path=right.as_posix() if right is not None else None,
        )
        if not snapshot_exists:
            raise DirdiffError(f"Unknown snapshot id: {snapshot_id.hex}")
        if loaded is None:
            raise DirdiffError("Snapshot manifest path is missing.")
        file = loaded.file
        directory = Path(file.path)
        assert directory.is_absolute(), (
            f"persisted Snapshot File path is not absolute: {file.path!r}"
        )
        result: list[Optional[Path]] = []
        for name, side in (("left", file.left), ("right", file.right)):
            if side is None:
                result.append(None)
                continue
            path = directory / name
            content = path.read_bytes()
            assert hashlib.sha256(content).digest() == side.content_hash, (
                f"Snapshot File content hash mismatch: {path}"
            )
            result.append(path)
        assert len(result) == 2
        match file.change_type:
            case "modify" | "add" | "delete" | "rename" | "copy":
                change_type = file.change_type
            case _:
                raise AssertionError(
                    f"invalid persisted File change type: {file.change_type!r}"
                )
        lazy_reason: Optional[LazyReason] = None
        if loaded.lazy_reason is not None:
            match loaded.lazy_reason:
                case (
                    "too_big"
                    | "generated"
                    | "deleted"
                    | "untracked"
                    | "pure_renamed"
                ):
                    lazy_reason = loaded.lazy_reason
                case _:
                    raise AssertionError(
                        f"invalid persisted lazy reason: {loaded.lazy_reason!r}"
                    )
        return (
            result[0],
            result[1],
            {
                "tracked": file.tracked,
                "change_type": change_type,
                "lazy_reason_override": lazy_reason,
                "capture_error": file.error,
            },
        )

    def file_delta(
        self, previous_snapshot_id: UUID, snapshot_id: UUID
    ) -> SnapshotFileDelta:
        """Compare persisted File-side hashes without rereading captured bytes."""
        snapshots = []
        for captured_id in (previous_snapshot_id, snapshot_id):
            snapshot = self._database.snapshot(self._identity, captured_id.hex)
            if snapshot is None:
                raise DirdiffError(f"Unknown snapshot id: {captured_id.hex}")
            snapshots.append(snapshot)

        def sides(
            snapshot: SnapshotRecord,
        ) -> dict[tuple[str, str], tuple[Path, bytes]]:
            """Index one retained Snapshot's present sides by stable path."""
            indexed: dict[tuple[str, str], tuple[Path, bytes]] = {}
            for file in snapshot.files:
                for side, record in (
                    ("left", file.left),
                    ("right", file.right),
                ):
                    if record is not None:
                        indexed[(side, record.repository_path)] = (
                            Path(file.path) / side,
                            record.content_hash,
                        )
            return indexed

        previous = sides(snapshots[0])
        current = sides(snapshots[1])
        return {
            "added": tuple(
                sorted(
                    current[key][0] for key in current.keys() - previous.keys()
                )
            ),
            "changed": tuple(
                sorted(
                    current[key][0]
                    for key in current.keys() & previous.keys()
                    if current[key][1] != previous[key][1]
                )
            ),
            "removed": tuple(
                sorted(
                    previous[key][0] for key in previous.keys() - current.keys()
                )
            ),
        }

    def captured_files_for_pairs(
        self,
        snapshot_id: UUID,
        pairs: tuple[tuple[Optional[str], Optional[str]], ...],
    ) -> dict[
        tuple[Optional[str], Optional[str]],
        tuple[Optional[Path], Optional[Path]],
    ]:
        """Return actual retained side paths for exactly the requested pairs.

        Each pair is a repository-path pair coming from this Room's own
        Thread placements, so an absent pair is an invariant violation, not
        caller input; an unknown Snapshot raises. One read and transaction
        serves every pair; contents are never read, and only the returned
        Files are stat-checked.
        """
        snapshot_exists, found = self._database.snapshot_files_by_pairs(
            self._identity,
            snapshot_id=snapshot_id.hex,
            pairs=pairs,
        )
        if not snapshot_exists:
            raise DirdiffError(f"Unknown snapshot id: {snapshot_id.hex}")
        result: dict[
            tuple[Optional[str], Optional[str]],
            tuple[Optional[Path], Optional[Path]],
        ] = {}
        for pair in dict.fromkeys(pairs):
            record = found.get(pair)
            assert record is not None, (
                "Thread location references a File absent from its Snapshot"
            )
            directory = Path(record.path)
            left_file = directory / "left" if record.left is not None else None
            right_file = (
                directory / "right" if record.right is not None else None
            )
            assert left_file is None or left_file.is_file()
            assert right_file is None or right_file.is_file()
            result[pair] = (left_file, right_file)
        return result

    def locate_captured_files(
        self, snapshot_id: UUID, captured: tuple[Path, ...]
    ) -> dict[
        Path,
        Optional[
            tuple[Optional[Path], Optional[Path], Literal["left", "right"]]
        ],
    ]:
        """Identify captured side paths as their repository pairs and sides.

        Every supplied path receives an entry; `None` means it does not name
        a captured side of this exact Snapshot. The captured layout is
        `<file-directory>/<side>` with the File id as the directory name; the
        persisted record's own directory must equal the supplied parent, so a
        lookalike path outside the Snapshot store never matches. One read
        serves every path; no side content is touched.
        """

        def parsed_file_id(path: Path) -> Optional[str]:
            """Extract the candidate File id when the path shape allows one."""
            if path.name != "left" and path.name != "right":
                return None
            file_id = path.parent.name
            if len(file_id) != 32 or any(
                character not in "0123456789abcdef" for character in file_id
            ):
                return None
            return file_id

        distinct = tuple(dict.fromkeys(captured))
        candidate_ids = tuple(
            dict.fromkeys(
                file_id
                for file_id in (parsed_file_id(path) for path in distinct)
                if file_id is not None
            )
        )
        records = self._database.snapshot_files_by_ids(
            self._identity,
            snapshot_id=snapshot_id.hex,
            file_ids=candidate_ids,
        )
        result: dict[
            Path,
            Optional[
                tuple[Optional[Path], Optional[Path], Literal["left", "right"]]
            ],
        ] = {}
        for path in distinct:
            result[path] = None
            file_id = parsed_file_id(path)
            if file_id is None:
                continue
            record = records.get(file_id)
            if record is None or Path(record.path) != path.parent:
                continue
            side: Literal["left", "right"] = (
                "left" if path.name == "left" else "right"
            )
            if (record.left if side == "left" else record.right) is None:
                continue
            left = (
                Path(record.left.repository_path)
                if record.left is not None
                else None
            )
            right = (
                Path(record.right.repository_path)
                if record.right is not None
                else None
            )
            result[path] = (left, right, side)
        return result

    def threads(
        self,
        snapshot_id: UUID,
        *,
        page: int,
        limit: int,
        state: Literal["all", "open"],
        through_activity_id: Optional[int],
        attention: Optional[Literal["author", "reviewer"]] = None,
    ) -> tuple[tuple[Thread, ...], int, int]:
        """Return one bounded Thread page and its inclusive activity pivot.

        `None` selects the latest Room activity in the same persistence read.
        Passing a returned concrete pivot makes later pages observe the same
        Thread existence, lifecycle state, ordering, count, and actions.
        """
        assert page >= 1 and limit >= 1
        return thread_objects(
            database=self._database,
            identity=self._identity,
            snapshot_id=snapshot_id,
            lock_path=self._lock_path,
            thread_lock=self._thread_lock,
            offset=(page - 1) * limit,
            limit=limit,
            state=state,
            attention=attention,
            through_activity_id=through_activity_id,
        )

    def get_thread(self, snapshot_id: UUID, thread_id: UUID) -> Thread:
        """Return one Thread bound to the exact Snapshot and Thread IDs."""
        return get_thread(
            database=self._database,
            identity=self._identity,
            snapshot_id=snapshot_id,
            thread_id=thread_id,
            lock_path=self._lock_path,
            thread_lock=self._thread_lock,
        )

    def thread_for_comment(self, snapshot_id: UUID, comment_id: UUID) -> Thread:
        """Return the bound Thread whose discussion contains one exact Comment.

        Comment-addressed HTTP writes know only the Comment key; this lookup
        locates its placed Thread in the exact Snapshot and returns it bound,
        or rejects an unknown Comment.
        """
        thread_id = self._database.review_thread_for_comment(
            snapshot_id.hex, comment_id.hex
        )
        if thread_id is None:
            raise ReviewError(
                "comment_not_found", f"Unknown Comment: {comment_id.hex}"
            )
        return self.get_thread(snapshot_id, UUID(hex=thread_id))

    def create_thread(
        self,
        snapshot_id: UUID,
        command: CreateThread,
    ) -> Thread:
        """Create one Thread in the exact Snapshot and return it bound."""
        return create_thread(
            database=self._database,
            identity=self._identity,
            snapshot_id=snapshot_id,
            command=command,
            lock_path=self._lock_path,
            thread_lock=self._thread_lock,
        )

    def latest_activity_id(self, snapshot_id: UUID) -> int:
        """Return the Room's current activity boundary without Thread hydration.

        The Snapshot must belong to this Room; the boundary is 0 for a Room
        with no review actions yet.
        """
        self.meta(snapshot_id)
        return self._database.review_latest_activity_id(self._identity)

    def continuation(
        self,
        snapshot_id: UUID,
        activity_id: int,
        limit: int,
    ) -> tuple[
        tuple[ReviewActionRecord, ...],
        bool,
        int,
        tuple[UserProfileRecord, ...],
    ]:
        """Return one bounded ordered page of later Thread changes.

        The page, has-more marker, open-Thread count, and acting Profiles are
        read consistently in one persistence read; the count holds at the
        page's inclusive end boundary.
        """
        self.meta(snapshot_id)
        return self._database.review_continuation(
            self._identity,
            activity_id,
            limit,
        )

    def review_attention_counts(
        self, snapshot_id: UUID, through_activity_id: int
    ) -> dict[Literal["author", "reviewer", "both"], int]:
        """Return actionable open-Thread counts at one activity boundary."""
        self.meta(snapshot_id)
        return self._database.review_attention_counts(
            self._identity, through_activity_id
        )

    def apply_review_batch(
        self,
        snapshot_id: UUID,
        batch: tuple[ReviewBatchAction, ...],
    ) -> tuple[ReviewBatchResult, ...]:
        """Apply one validated agent batch in a single database transaction."""
        return apply_review_batch(
            database=self._database,
            identity=self._identity,
            snapshot_id=snapshot_id,
            batch=batch,
            lock_path=self._lock_path,
            thread_lock=self._thread_lock,
        )

    def capture_context(self) -> RoomCaptureContext:
        """Return the repository context required to continue this Room.

        The HTTP boundary needs the Mark and any Pull Request URL to construct
        the concrete backend and prepared commits before `recapture` runs.
        Preset Rooms have no repository to continue and are rejected.
        """
        identity = self._identity
        if identity.mark_id is None or identity.tab == "preset":
            raise DirdiffError("Agent review does not support preset Rooms.")
        try:
            correspondence = json.loads(identity.correspondence_key)
        except (TypeError, ValueError) as exc:
            raise AssertionError(
                "invalid persisted Room correspondence"
            ) from exc
        match identity.tab:
            case "head" | "refs" | "branch-review":
                assert isinstance(correspondence, dict)
                tab: Literal[
                    "head", "refs", "branch-review", "pull-request"
                ] = identity.tab
                pull_request_url = None
            case "pull-request":
                tab = "pull-request"
                assert isinstance(correspondence, str) and correspondence != ""
                pull_request_url = correspondence
            case _:
                raise AssertionError(
                    f"invalid persisted Room Tab: {identity.tab!r}"
                )
        return {
            "tab": tab,
            "mark_id": identity.mark_id,
            "pull_request_url": pull_request_url,
        }

    def recapture(
        self,
        backend: WorkspaceBackendProtocol,
        *,
        pull_request_left: Optional[str] = None,
        pull_request_right: Optional[str] = None,
    ) -> UUID:
        """Capture this Room's persisted Tab context into a new Snapshot.

        The concrete backend comes from the HTTP boundary's active Mark. A Pull
        Request continuation must supply the newly prepared complete commits;
        other Tabs reject them. The new Snapshot remains in this exact Room.
        """
        identity = self._identity
        if identity.mark_id is None or identity.tab == "preset":
            raise DirdiffError("Agent review does not support preset Rooms.")
        try:
            correspondence = json.loads(identity.correspondence_key)
        except (TypeError, ValueError) as exc:
            raise AssertionError(
                "invalid persisted Room correspondence"
            ) from exc
        assert isinstance(backend, GitBackend)
        left_side: str
        right_side: str

        if identity.tab == "pull-request":
            assert isinstance(correspondence, str) and correspondence != ""
        else:
            assert isinstance(correspondence, dict)

        def persisted_branch(value: object) -> BranchSelection:
            """Validate one structured branch stored in correspondence JSON."""
            assert isinstance(value, dict)
            source = value.get("source")
            branch = value.get("branch")
            assert isinstance(branch, str) and branch != ""
            if source == "local":
                return {"source": "local", "branch": branch}
            assert source == "remote"
            remote = value.get("remote")
            assert isinstance(remote, str) and remote != ""
            return {
                "source": "remote",
                "remote": remote,
                "branch": branch,
            }

        if identity.tab == "head":
            assert pull_request_left is None and pull_request_right is None
            stored_commit = correspondence.get("commit")
            assert isinstance(stored_commit, str) and stored_commit != ""
            left_side = stored_commit
            right_side = "worktree"
            left_label = "HEAD"
            right_label = "worktree"
            show_untracked = True
        elif identity.tab == "refs":
            assert pull_request_left is None and pull_request_right is None
            stored_left = correspondence.get("left")
            stored_right = correspondence.get("right")
            assert isinstance(stored_left, str) and stored_left != ""
            assert isinstance(stored_right, str) and stored_right != ""
            left_side = stored_left
            right_side = stored_right
            left_label = left_side
            right_label = right_side
            show_untracked = False
        elif identity.tab == "branch-review":
            assert pull_request_left is None and pull_request_right is None
            base_value = correspondence.get("base")
            review_value = correspondence.get("review")
            resolved_base, left_side, review_side, right_side = (
                backend.resolve_branch_diff_sides(
                    base_selection=persisted_branch(base_value),
                    review_selection=persisted_branch(review_value),
                )
            )
            left_label = f"{resolved_base.strip()}...{review_side}"
            right_label = review_side
            show_untracked = False
        else:
            assert identity.tab == "pull-request"
            if pull_request_left is None or pull_request_right is None:
                raise DirdiffError(
                    "Pull Request continuation requires prepared commits."
                )
            left_side = backend.commit_id(pull_request_left)
            right_side = backend.commit_id(pull_request_right)
            if (
                left_side != pull_request_left
                or right_side != pull_request_right
            ):
                raise DirdiffError(
                    "Pull Request continuation requires complete commit ids."
                )
            left_label = left_side
            right_label = right_side
            show_untracked = False

        store = _SnapshotStore(
            database=self._database,
            staging_path=self._staging_path,
            snapshots_path=self._snapshots_path,
            lock_path=self._lock_path,
            thread_lock=self._thread_lock,
            identity=identity,
        )
        return store.capture(
            backend=backend,
            left_side=left_side,
            right_side=right_side,
            left_label=left_label,
            right_label=right_label,
            show_untracked=show_untracked,
        )

    def path_for_snapshot(self, snapshot_id: UUID) -> Path:
        """Return the existing durable directory of one captured Snapshot.

        The key must identify a persisted Snapshot of this Room. This read
        exposes the directory already published by ordinary Snapshot capture
        and creates no file, directory, link, row, or alternative
        representation.
        """
        self.meta(snapshot_id)
        path = self._snapshots_path / snapshot_id.hex
        assert path.is_dir(), f"Snapshot directory is missing: {path}"
        return path


class RoomLord:
    """Apply the active Tab's law of correspondence and return a Room.

    `corresponding_room` applies the law for one explicit capture and returns
    both the Room and the captured Snapshot key. `find_room` uses an existing
    Snapshot key to recover its Room for follow-up operations. Neither method
    exposes the private Snapshot store; every other Room operation belongs to
    the returned Room.
    """

    def __init__(self, database: RoomStore, store_path: Path) -> None:
        """Create the application boundary for one database and store root.

        The paths are normalized but not created here. This keeps construction
        harmless; the first valid manifest capture creates storage only after
        repository-placement checks succeed.
        """
        self._database = database
        self._store_path = store_path.expanduser().resolve()
        self._staging_path = self._store_path / "staging"
        self._snapshots_path = self._store_path / "snapshots"
        database_path = self._database.engine.url.database
        if database_path is None or database_path == ":memory:":
            self._lock_path = self._store_path / "store.lock"
        else:
            database_file = Path(database_path).expanduser().resolve()
            self._lock_path = database_file.with_name(
                f"{database_file.name}.room.lock"
            )
        # `flock` coordinates processes; this lock gives worker threads one
        # unambiguous publication critical section.
        self._thread_lock = Lock()

    def corresponding_room(
        self,
        *,
        mark_id: Optional[int],
        backend: WorkspaceBackendProtocol,
        selection: CaptureSelection,
    ) -> tuple[Room, UUID]:
        """Apply one Tab's law and return its Room and current Snapshot key.

        The selection variant carries exactly its Tab's inputs, so validity
        checks concern values, never cross-Tab absence. The law of
        correspondence selects only the Room. The independently derived sides
        are supplied to Snapshot capture after that Room identity is
        complete.
        """
        repo_root = backend.repo_root
        if mark_id is not None and repo_root is not None:
            reviewed_root = repo_root.resolve()
            database = self._database.engine.url.database
            if database is not None and database != ":memory:":
                database_path = Path(database).expanduser().resolve()
                if database_path.is_relative_to(reviewed_root):
                    raise DirdiffError(
                        "The dirdiff database must be outside the reviewed "
                        f"repository: {database_path}"
                    )
            if self._store_path.is_relative_to(reviewed_root):
                raise DirdiffError(
                    "The dirdiff Snapshot store must be outside the reviewed "
                    f"repository: {self._store_path}"
                )

        tab: RoomTab
        show_untracked = False
        git_backend: Optional[GitBackend] = None
        if not isinstance(selection, PresetCaptureSelection):
            assert isinstance(backend, GitBackend), (
                "repository Rooms require GitBackend"
            )
            git_backend = backend

        if isinstance(selection, PresetCaptureSelection):
            tab = "preset"
            assert mark_id is None, "preset Rooms cannot belong to a Mark"
            if (catalog := selection.catalog.strip()) == "":
                raise DirdiffError(
                    "preset_catalog is required for the Preset Tab."
                )
            if (subset := selection.subset.strip()) == "":
                raise DirdiffError(
                    "preset_subset is required for the Preset Tab."
                )
            left_side = backend.normalize_side(subset)
            right_side = "new"
            left_label = "old"
            right_label = "new"
            correspondence: object = {"catalog": catalog, "subset": subset}
        elif isinstance(selection, PullRequestCaptureSelection):
            tab = "pull-request"
            assert mark_id is not None, "Pull Request Rooms require a Mark"
            if (corresponding_url := selection.url.strip()) == "":
                raise DirdiffError(
                    "pull_request_url is required for the Pull Request Tab."
                )
            if (prepared_left := selection.left_commit.strip()) == "":
                raise DirdiffError(
                    "left_commit is required for the Pull Request Tab."
                )
            if (prepared_right := selection.right_commit.strip()) == "":
                raise DirdiffError(
                    "right_commit is required for the Pull Request Tab."
                )
            assert git_backend is not None
            left_side = git_backend.commit_id(prepared_left)
            right_side = git_backend.commit_id(prepared_right)
            if left_side != prepared_left or right_side != prepared_right:
                raise DirdiffError(
                    "Pull Request capture inputs must be complete commit ids."
                )
            left_label = left_side
            right_label = right_side
            correspondence = corresponding_url
        elif isinstance(selection, BranchReviewCaptureSelection):
            tab = "branch-review"
            assert mark_id is not None, "Branch Review Rooms require a Mark"
            assert git_backend is not None
            resolved_base, left_side, review, right_side = (
                git_backend.resolve_branch_diff_sides(
                    base_selection=selection.base,
                    review_selection=selection.review,
                )
            )
            left_label = f"{resolved_base.strip()}...{review}"
            right_label = review
            correspondence = {
                "base": selection.base,
                "review": selection.review,
            }
        elif selection.tab == "head":
            tab = "head"
            show_untracked = selection.show_untracked
            assert mark_id is not None, "Diff against HEAD requires a Mark"
            left_label = backend.normalize_side(selection.left.strip())
            right_label = backend.normalize_side(selection.right.strip())
            if left_label != "HEAD" or right_label != "worktree":
                raise DirdiffError(
                    "Diff against HEAD requires left=HEAD and right=worktree."
                )
            assert git_backend is not None
            left_side = git_backend.commit_id(left_label)
            right_side = right_label
            correspondence = {"commit": left_side}
        else:
            assert selection.tab == "refs"
            tab = "refs"
            show_untracked = selection.show_untracked
            assert mark_id is not None, "repo Rooms require a Mark"
            assert git_backend is not None
            if selection.left.strip() == "":
                raise DirdiffError("left is required for the Refs Tab.")
            if selection.right.strip() == "":
                raise DirdiffError("right is required for the Refs Tab.")
            left_label = backend.normalize_side(selection.left.strip())
            right_label = backend.normalize_side(selection.right.strip())
            left_side = (
                left_label
                if left_label in {"index", "worktree"}
                else git_backend.commit_id(left_label)
            )
            right_side = (
                right_label
                if right_label in {"index", "worktree"}
                else git_backend.commit_id(right_label)
            )
            left_label = left_side
            right_label = right_side
            correspondence = {"left": left_side, "right": right_side}

        identity = RoomIdentity(
            mark_id=mark_id,
            tab=tab,
            correspondence_key=json.dumps(
                correspondence,
                sort_keys=True,
                separators=(",", ":"),
            ).encode(),
        )
        store = _SnapshotStore(
            database=self._database,
            staging_path=self._staging_path,
            snapshots_path=self._snapshots_path,
            lock_path=self._lock_path,
            thread_lock=self._thread_lock,
            identity=identity,
        )
        snapshot_id = store.capture(
            backend=backend,
            left_side=left_side,
            right_side=right_side,
            left_label=left_label,
            right_label=right_label,
            show_untracked=show_untracked,
        )
        return Room(
            database=self._database,
            identity=identity,
            staging_path=self._staging_path,
            snapshots_path=self._snapshots_path,
            lock_path=self._lock_path,
            thread_lock=self._thread_lock,
        ), snapshot_id

    def find_room(self, snapshot_id: UUID) -> Room:
        """Return the Room containing an existing Snapshot key.

        The Snapshot id is globally unique in this database. Missing keys are
        rejected; this lookup neither executes a Tab law nor reads live backend
        state.
        """
        identity = self._database.room_identity(snapshot_id.hex)
        if identity is None:
            raise DirdiffError(f"Unknown snapshot id: {snapshot_id.hex}")
        if identity.tab not in {
            "head",
            "refs",
            "branch-review",
            "pull-request",
            "preset",
        }:
            raise AssertionError(
                f"invalid persisted Room Tab: {identity.tab!r}"
            )
        return Room(
            database=self._database,
            identity=identity,
            staging_path=self._staging_path,
            snapshots_path=self._snapshots_path,
            lock_path=self._lock_path,
            thread_lock=self._thread_lock,
        )


class _SnapshotStore:
    """Implement immutable Snapshot capture for one private Room.

    `RoomLord.corresponding_room` and `Room.recapture` construct and call the
    store for exactly one capture. It manages publication directories, locking,
    relational records, and digest validation; API code never receives it.
    """

    def __init__(
        self,
        *,
        database: RoomStore,
        staging_path: Path,
        snapshots_path: Path,
        lock_path: Path,
        thread_lock: Lock,
        identity: RoomIdentity,
    ) -> None:
        """Create private persistence access for exactly one Room identity.

        `RoomLord` supplies shared paths and locking, while `identity` limits
        every relational lookup. Constructing the store performs no filesystem
        or database work.
        """
        assert identity.correspondence_key != b"", (
            "Room correspondence key cannot be empty"
        )
        self._database = database
        self._staging_path = staging_path
        self._snapshots_path = snapshots_path
        self._lock_path = lock_path
        self._thread_lock = thread_lock
        self._identity = identity

    def capture(
        self,
        *,
        backend: WorkspaceBackendProtocol,
        left_side: str,
        right_side: str,
        left_label: str,
        right_label: str,
        show_untracked: bool,
    ) -> UUID:
        """Capture current backend state and return its retained Snapshot key.

        Equality includes repository paths, tracked provenance, change type,
        captured contents, capture errors, and complete explicit preset metadata.
        Backend order, human labels, and aggregate line counts do not affect
        identity. Every Thread contained by the Room is placed in the captured
        Snapshot before it becomes visible.
        """
        self._staging_path.mkdir(parents=True, exist_ok=True)
        self._snapshots_path.mkdir(parents=True, exist_ok=True)
        self._lock_path.touch(exist_ok=True)

        diff = backend.repo_diff(
            left=left_side,
            right=right_side,
            show_untracked=show_untracked,
        )
        paths = diff.paths
        added_lines = diff.added_lines
        removed_lines = diff.removed_lines
        assert (added_lines is None) == (removed_lines is None), (
            "backend aggregate line counts must have equal presence"
        )
        normalized_paths: list[
            tuple[
                Optional[str],
                Optional[str],
                bool,
                ChangeType,
                Optional[LazyReason],
                Optional[str],
                Optional[str],
            ]
        ] = []
        captured_paths: set[tuple[Optional[str], Optional[str]]] = set()
        for path in paths:
            repository_paths = (path.left_path, path.right_path)
            if repository_paths in captured_paths:
                raise DirdiffError(
                    "Backend returned duplicate left/right paths: "
                    f"{repository_paths!r}"
                )
            captured_paths.add(repository_paths)
            left_path = (
                backend.normalize_repo_path(path.left_path)
                if path.left_path is not None
                else None
            )
            right_path = (
                backend.normalize_repo_path(path.right_path)
                if path.right_path is not None
                else None
            )
            normalized_paths.append(
                (
                    left_path,
                    right_path,
                    not path.untracked,
                    path.change_type,
                    path.lazy_reason_override,
                    path.left_object_id,
                    path.right_object_id,
                )
            )

        # Sides carrying a backend object id participate in Snapshot identity
        # by that id, so their bytes are read only when the Snapshot turns out
        # to be new. Only object-id-less sides (worktree, index gaps,
        # untracked files, preset fixtures) are read before the retained
        # check. A failed eager read substitutes the established error
        # content, so eager errors stay part of identity through the content
        # token; a deferred side's identity IS its object id, and a later
        # read failure no longer creates a distinct error Snapshot identity.
        eager_requests: list[tuple[str, str]] = []
        for (
            left_path,
            right_path,
            _tracked,
            _change_type,
            _lazy_reason_override,
            left_object_id,
            right_object_id,
        ) in normalized_paths:
            if left_path is not None and left_object_id is None:
                eager_requests.append((left_path, left_side))
            if right_path is not None and right_object_id is None:
                eager_requests.append((right_path, right_side))
        eager_versions = iter(backend.load_versions(tuple(eager_requests)))

        # Per file: side slots hold loaded bytes for eager sides and None for
        # deferred object-id sides; error strings collect per file in side
        # order exactly as the previous single-pass capture did.
        interim: list[
            tuple[
                Optional[str],
                Optional[bytes],
                Optional[str],
                Optional[str],
                Optional[bytes],
                Optional[str],
                bool,
                ChangeType,
                Optional[LazyReason],
                Optional[str],
                list[str],
            ]
        ] = []

        def substituted_side(
            loaded: bytes | DirdiffError,
            side_path: str,
            side_name: str,
            side_label: str,
            errors: list[str],
        ) -> bytes:
            """Return one loaded side, substituting the established error text."""
            if isinstance(loaded, DirdiffError):
                failure = (
                    f"Could not capture {side_name} side "
                    f"{side_label}:{side_path}: {loaded}"
                )
                errors.append(failure)
                return f"{_CAPTURE_ERROR_PREAMBLE}\n\n{failure}\n".encode()
            return loaded

        for (
            left_path,
            right_path,
            tracked,
            change_type,
            lazy_reason_override,
            left_object_id,
            right_object_id,
        ) in normalized_paths:
            errors: list[str] = []
            left_content: Optional[bytes] = None
            if left_path is not None and left_object_id is None:
                left_content = substituted_side(
                    next(eager_versions), left_path, "left", left_side, errors
                )
            right_content: Optional[bytes] = None
            if right_path is not None and right_object_id is None:
                right_content = substituted_side(
                    next(eager_versions),
                    right_path,
                    "right",
                    right_side,
                    errors,
                )
            assert left_path is not None or right_path is not None, (
                "Snapshot File must have at least one side"
            )

            lazy_metadata: Optional[tuple[LazyReason, str]] = None
            if self._identity.tab == "preset":
                assert isinstance(backend, PresetBackend), (
                    "preset Rooms require PresetBackend"
                )
                assert right_path is not None, (
                    "preset Files require a right repository path"
                )
                lazy_metadata = backend.lazy_reason_metadata(right_path)
                assert (
                    lazy_metadata[0] if lazy_metadata is not None else None
                ) == lazy_reason_override, (
                    "preset lazy reason changed during Snapshot capture"
                )
            else:
                assert lazy_metadata is None
            interim.append(
                (
                    left_path,
                    left_content,
                    left_object_id,
                    right_path,
                    right_content,
                    right_object_id,
                    tracked,
                    change_type,
                    lazy_reason_override,
                    lazy_metadata[1] if lazy_metadata is not None else None,
                    errors,
                )
            )
        try:
            next(eager_versions)
        except StopIteration:
            pass
        else:
            raise AssertionError("backend returned excess captured sides")

        # Canonicalization makes the digest describe a set of Files; it does
        # not define storage or manifest presentation order. Each present side
        # contributes one identity token: its backend object id when it has
        # one, otherwise its captured bytes (which already embed any eager
        # read failure).
        interim.sort(key=lambda item: (item[0] or "", item[3] or ""))
        digest = hashlib.sha256()
        digest.update(_SNAPSHOT_HASH_DOMAIN)
        for (
            left_path,
            left_content,
            left_object_id,
            right_path,
            right_content,
            right_object_id,
            tracked,
            change_type,
            lazy_reason,
            metadata_content,
            _errors,
        ) in interim:

            def side_token(
                content: Optional[bytes], object_id: Optional[str]
            ) -> Optional[bytes]:
                """Encode one side's identity token, or None for an absent side."""
                if object_id is not None:
                    return b"O" + object_id.encode("ascii")
                if content is not None:
                    return b"C" + content
                return None

            for value in (
                left_path.encode() if left_path is not None else None,
                side_token(left_content, left_object_id),
                right_path.encode() if right_path is not None else None,
                side_token(right_content, right_object_id),
                b"1" if tracked else b"0",
                change_type.encode(),
                lazy_reason.encode() if lazy_reason is not None else None,
                metadata_content.encode()
                if metadata_content is not None
                else None,
            ):
                if value is None:
                    digest.update(b"\x00")
                else:
                    digest.update(b"\x01")
                    digest.update(len(value).to_bytes(8, "big"))
                    digest.update(value)
        snapshot_hash = digest.digest()

        def verified_retained_snapshot(snapshot_id: str) -> UUID:
            """Return one retained Snapshot after verifying every stored side."""
            visible_snapshot = self._database.snapshot(
                self._identity,
                snapshot_id,
            )
            assert visible_snapshot is not None, (
                "equal Snapshot disappeared during publication"
            )
            for file in visible_snapshot.files:
                directory = Path(file.path)
                for name, side in (
                    ("left", file.left),
                    ("right", file.right),
                ):
                    if side is None:
                        continue
                    captured_path = directory / name
                    content = captured_path.read_bytes()
                    assert (
                        hashlib.sha256(content).digest() == side.content_hash
                    ), f"Snapshot File content hash mismatch: {captured_path}"
            return UUID(hex=snapshot_id)

        retained_id = self._database.snapshot_id_for_content(
            self._identity,
            snapshot_hash,
        )
        if retained_id is not None:
            return verified_retained_snapshot(retained_id)

        # The Snapshot is new: read the deferred object-id sides and assemble
        # the complete captured rows the storage loop below persists.
        deferred_requests: list[tuple[str, str]] = []
        for (
            left_path,
            _left_content,
            left_object_id,
            right_path,
            _right_content,
            right_object_id,
            *_rest,
        ) in interim:
            if left_path is not None and left_object_id is not None:
                deferred_requests.append((left_path, left_side))
            if right_path is not None and right_object_id is not None:
                deferred_requests.append((right_path, right_side))
        deferred_versions = iter(
            backend.load_versions(tuple(deferred_requests))
        )
        captured: list[
            tuple[
                Optional[str],
                Optional[bytes],
                Optional[str],
                Optional[bytes],
                bool,
                ChangeType,
                Optional[LazyReason],
                Optional[str],
                Optional[str],
            ]
        ] = []

        def deferred_side(
            loaded: bytes | DirdiffError,
            side_path: str,
            side_name: str,
            side_label: str,
        ) -> bytes:
            """Return one object-id side's bytes, failing the capture on error.

            The side's object id already joined the Snapshot's identity, so a
            failed read must abort the capture: substituting error content
            here would persist an error placeholder under an identity token
            that names the real bytes, and every later capture of the same
            state would reuse the poisoned Snapshot without re-reading the
            backend. The id-addressed object is immutable, so the failure is
            infrastructural and a retry captures cleanly.
            """
            if isinstance(loaded, DirdiffError):
                raise DirdiffError(
                    f"Could not capture {side_name} side "
                    f"{side_label}:{side_path}: {loaded}"
                )
            return loaded

        for (
            left_path,
            left_content,
            left_object_id,
            right_path,
            right_content,
            right_object_id,
            tracked,
            change_type,
            lazy_reason_override,
            metadata_content,
            errors,
        ) in interim:
            full_left = left_content
            if left_path is not None and left_object_id is not None:
                full_left = deferred_side(
                    next(deferred_versions), left_path, "left", left_side
                )
            full_right = right_content
            if right_path is not None and right_object_id is not None:
                full_right = deferred_side(
                    next(deferred_versions), right_path, "right", right_side
                )
            assert (left_path is None) == (full_left is None), (
                "left repository path and captured contents must have equal presence"
            )
            assert (right_path is None) == (full_right is None), (
                "right repository path and captured contents must have equal presence"
            )
            assert full_left is not None or full_right is not None, (
                "Snapshot File must have at least one side"
            )
            captured.append(
                (
                    left_path,
                    full_left,
                    right_path,
                    full_right,
                    tracked,
                    change_type,
                    lazy_reason_override,
                    metadata_content,
                    "\n".join(errors) if errors else None,
                )
            )
        try:
            next(deferred_versions)
        except StopIteration:
            pass
        else:
            raise AssertionError("backend returned excess captured sides")

        snapshot_id = uuid4()
        staging_path = Path(
            tempfile.mkdtemp(
                prefix=f"{snapshot_id.hex}-",
                dir=self._staging_path,
            )
        )
        final_path = (self._snapshots_path / snapshot_id.hex).resolve()
        files: list[SnapshotFileRecord] = []
        lazy_reasons: dict[str, tuple[str, Optional[str]]] = {}
        try:
            for (
                left_path,
                left_content,
                right_path,
                right_content,
                tracked,
                change_type,
                lazy_reason,
                metadata_content,
                error,
            ) in captured:
                file_id = uuid4().hex
                file_path = staging_path / file_id
                file_path.mkdir()
                left_record: Optional[SnapshotFileSideRecord] = None
                if left_path is not None and left_content is not None:
                    (file_path / "left").write_bytes(left_content)
                    left_record = SnapshotFileSideRecord(
                        repository_path=left_path,
                        content_hash=hashlib.sha256(left_content).digest(),
                    )
                right_record: Optional[SnapshotFileSideRecord] = None
                if right_path is not None and right_content is not None:
                    (file_path / "right").write_bytes(right_content)
                    right_record = SnapshotFileSideRecord(
                        repository_path=right_path,
                        content_hash=hashlib.sha256(right_content).digest(),
                    )
                files.append(
                    SnapshotFileRecord(
                        id=file_id,
                        snapshot_id=snapshot_id.hex,
                        path=str(final_path / file_id),
                        tracked=tracked,
                        change_type=change_type,
                        error=error,
                        left=left_record,
                        right=right_record,
                    )
                )
                if lazy_reason is not None:
                    lazy_reasons[file_id] = lazy_reason, metadata_content

            with self._thread_lock, self._lock_path.open("a+b") as lock_file:
                fcntl.flock(lock_file.fileno(), fcntl.LOCK_EX)
                try:
                    visible_id = self._database.snapshot_id_for_content(
                        self._identity,
                        snapshot_hash,
                    )
                    if visible_id is None:
                        published_snapshot = SnapshotRecord(
                            id=snapshot_id.hex,
                            content_hash=snapshot_hash,
                            meta=SnapshotMetaRecord(
                                left_label=left_label,
                                right_label=right_label,
                                added_lines=added_lines,
                                removed_lines=removed_lines,
                            ),
                            files=tuple(files),
                        )
                        # Thread derivation reads the target Snapshot's own
                        # captured text (region relocation), so the bytes must
                        # already sit at their final address before it runs.
                        staging_path.rename(final_path)
                        try:
                            review_threads = derive_room_threads(
                                database=self._database,
                                identity=self._identity,
                                target_snapshot=published_snapshot,
                            )
                            self._database.publish(
                                self._identity,
                                published_snapshot,
                                lazy_reasons=lazy_reasons,
                                review_threads=review_threads,
                            )
                        except BaseException:
                            # Derivation or publication failed after the
                            # rename: restore the staging address so cleanup
                            # removes the bytes and no orphaned, untracked
                            # Snapshot directory survives at its published
                            # address. Publication itself is one transaction,
                            # so no database rows exist either way.
                            final_path.rename(staging_path)
                            raise
                        visible_id = snapshot_id.hex
                    else:
                        return verified_retained_snapshot(visible_id)
                    return UUID(hex=visible_id)
                finally:
                    fcntl.flock(lock_file.fileno(), fcntl.LOCK_UN)
        finally:
            if staging_path.exists():
                shutil.rmtree(staging_path)
